import argparse
import os


# Fixed variable name used in main.cpp — do not change without updating firmware
MODEL_ARRAY_NAME = "g_model_data"


def convert(tflite_path: str, output_path: str) -> None:
    """
    Converts a .tflite file into a C source file (.cc) containing the model
    as a byte array aligned to 8 bytes, required by TFLM's GetModel().

    The array is always named g_model_data to match the firmware reference
    in main.cpp. A companion header declares the extern symbols.
    """
    with open(tflite_path, "rb") as f:
        data = f.read()

    model_size = len(data)

    # --- Write the .cc file (definition) ---
    cc_lines = []
    cc_lines.append('#include "model_data.h"')
    cc_lines.append("")
    cc_lines.append(f"// Source: {tflite_path}")
    cc_lines.append(f"// Model size: {model_size} bytes ({model_size / 1024:.1f} KB)")
    cc_lines.append("")
    cc_lines.append(f"const uint32_t {MODEL_ARRAY_NAME}_len = {model_size};")
    cc_lines.append("")
    cc_lines.append(f"alignas(8) const uint8_t {MODEL_ARRAY_NAME}[] = {{")

    for i in range(0, model_size, 12):
        chunk = data[i:i + 12]
        hex_values = ", ".join(f"0x{b:02x}" for b in chunk)
        cc_lines.append(f"  {hex_values},")

    cc_lines.append("};")
    cc_lines.append("")

    # --- Write the .h file (extern declarations) ---
    h_lines = []
    h_lines.append("#pragma once")
    h_lines.append("#include <stdint.h>")
    h_lines.append("")
    h_lines.append(f"// Auto-generated by convert_to_c_array.py")
    h_lines.append(f"// Source: {tflite_path}")
    h_lines.append("")
    h_lines.append(f"extern const uint32_t {MODEL_ARRAY_NAME}_len;")
    h_lines.append(f"extern const uint8_t  {MODEL_ARRAY_NAME}[];")
    h_lines.append("")

    # Safe makedirs: os.path.dirname returns "" if no directory component
    out_dir = os.path.dirname(output_path)
    if out_dir:
        os.makedirs(out_dir, exist_ok=True)

    # output_path is the .cc path; derive .h path from it
    h_path = os.path.splitext(output_path)[0] + ".h"

    with open(output_path, "w") as f:
        f.write("\n".join(cc_lines))

    with open(h_path, "w") as f:
        f.write("\n".join(h_lines))

    print(f"Written : {output_path}")
    print(f"Written : {h_path}")
    print(f"  Array name  : {MODEL_ARRAY_NAME}")
    print(f"  Model size  : {model_size} bytes ({model_size / 1024:.1f} KB)")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Convert a .tflite model to a C array for TFLM firmware."
    )
    parser.add_argument("--tflite", required=True, help="Path to input .tflite file")
    parser.add_argument("--output", required=True, help="Path to output .cc file (e.g. src/model_data.cc)")
    args = parser.parse_args()

    convert(args.tflite, args.output)